# Generated by Django 3.0.3 on 2020-02-29 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booi_operations', '0002_auto_20200229_1645'),
        ('handelbyadmin', '0001_initial'),
        ('local_users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttoborrower',
            name='investigator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporttoborrower',
            name='report_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_users.UserProfile'),
        ),
        migrations.AddField(
            model_name='reporttobookowner',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booi_operations.Booi'),
        ),
        migrations.AddField(
            model_name='reporttobookowner',
            name='investigator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporttobookowner',
            name='report_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_users.UserProfile'),
        ),
        migrations.AddField(
            model_name='notification',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booi_operations.Booi'),
        ),
        migrations.AddField(
            model_name='faq',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='local_users.UserProfile'),
        ),
    ]
