# Generated by Django 3.0.3 on 2020-02-29 10:45

import booi_operations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=booi_operations.models.get_uplaod_file_name)),
                ('booiName', models.CharField(max_length=255)),
                ('booiAuthor', models.CharField(max_length=255)),
                ('booiCategory', models.CharField(max_length=255)),
                ('booiCondition', models.CharField(choices=[('Good', 'ভাল'), ('Average', 'মোটামুটি'), ('Bad', 'খারাপ')], max_length=255)),
                ('available', models.BooleanField(default=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('brief', models.TextField(blank=True, null=True)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('borrowedTimes', models.IntegerField(default=0)),
                ('acceptByAdmin', models.BooleanField(default=False)),
                ('deleteRequest', models.BooleanField(default=False)),
                ('finally_publish', models.BooleanField(default=False)),
                ('search_keyword', models.CharField(blank=True, max_length=2055, null=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=2055, null=True)),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='LendBooi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('securityToken', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('returnToken', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('borrowed', models.BooleanField(default=False)),
                ('search_keyword', models.CharField(blank=True, max_length=2055, null=True)),
                ('generateTokenTime', models.DateTimeField(auto_now=True)),
                ('borrowBookTime', models.DateTimeField(blank=True, null=True)),
                ('returnWithin', models.DateTimeField(blank=True, null=True)),
                ('returnBook', models.BooleanField(default=False)),
                ('returnTime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-borrowBookTime', '-generateTokenTime'],
            },
        ),
    ]
