# Generated by Django 3.0.3 on 2020-02-29 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booi_operations', '0001_initial'),
        ('local_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendbooi',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_users.UserProfile'),
        ),
        migrations.AddField(
            model_name='lendbooi',
            name='thisBooi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booi_operations.Booi'),
        ),
        migrations.AddField(
            model_name='booi',
            name='booiOwner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_users.UserProfile'),
        ),
    ]
